# Generated by Django 3.2.4 on 2024-07-09 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_template'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Template',
            new_name='CustomTemplates',
        ),
    ]
