# Generated by Django 3.2.4 on 2024-08-04 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20240723_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualities',
            name='extracirricular',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
