# Generated by Django 5.1.7 on 2025-03-23 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_qualities_extracirricular'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='linkedIn',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='personal_statement',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='recommendation_purpose',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
