# Generated by Django 5.1.7 on 2025-07-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_application_linkedin_application_personal_statement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentlogininfo',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='student_photos/'),
        ),
    ]
