# Generated by Django 5.1.7 on 2025-07-27 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_studentlogininfo_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtemplates',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
