# Generated by Django 5.1.7 on 2026-03-01 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_customtemplates_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='class_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='competitions_won',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='intern_company',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='intern_duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='intern_outcome',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='intern_role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='language_instruction',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='prof_anecdote',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='ranking_percentile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='relationship_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='scholarships',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qualities',
            name='recommendation_strength',
            field=models.CharField(blank=True, choices=[('top5', 'Top 5%'), ('top10', 'Top 10%'), ('outstanding', 'Outstanding'), ('strong', 'Strong')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teacherinfo',
            name='designation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teacherinfo',
            name='office_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
